### ISSUE TITLE
Checking versioning on new PRs

### ISSUE THREAD

**Issue by adecler** [BHoM/admin#12]
#### Description:
It would be great to automaticalyl check that versioning is correct (and provided) on new PRs.

As suggested by @al-fisher: we could just serialise the objects and methods from the master and the deserialise them from the PR. The trick is going to filer the objects and methods that need to be tested.

**Comment by FraserGreenroyd** [comment]
This has now been implemented with a `@BHoMBot check versioning` command available for PRs. Needs to be examined as it's used to make sure it's doing the right thing, but follows the principle above with the measure of success against the existing state.
