### ISSUE TITLE
check documentation compliance fails with multiple PreviousVersion

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/admin#14]
#### Description:

The BHoMBot check documentation compliance fails when there are two lines of PreviousVersion in the code. Tested that removing one line will pass the check. 

#### Test file(s):

https://github.com/BHoM/MachineLearning_Toolkit/pull/80

**Comment by FraserGreenroyd** [comment]
@BingWangUS FYI this will be resolved by https://github.com/BHoM/Test_Toolkit/pull/328

For future reference can issues like this be raised on Test Toolkit :smile:
