### ISSUE TITLE
Creation of CustomObject with key of 'id'

### ISSUE THREAD

**Issue by jamesramsden-bh** [BHoM/admin#18]
Create a custom object with a dictionary item where the key is exactly `id`. The CustomObject appears to be constructed without error, but inspection of the CustomObject shows that the row with key=`id` has disappeared. 

This either needs fixing (allow the dictionary to be created correctly), or (under my suspicion that id should actually be protected) an error should be thrown and the user should be advised to review their dictionary key names. 

Example of current CustomObject creation. Note that exploding does not show a key of id. 

![image](https://user-images.githubusercontent.com/84443868/145257358-e397774b-76a3-49df-ba17-cae86f3437a0.png)

**Comment by IsakNaslundBh** [comment]
@jamesramsden-bh this works without any issue on my machine:
![image](https://user-images.githubusercontent.com/22005920/147213556-a5eb8b61-8923-4ecc-86e0-f6d3a62686d5.png)

Could you try rightclicking the explode and choose "UpdateOutputs" to make sure the explode component is up to date?

ALso worth checking what if you can acess the object using GetProperty:

![image](https://user-images.githubusercontent.com/22005920/147213773-219887d9-afd1-417e-bb73-a74a2713527e.png)

**Comment by jamesramsden-bh** [comment]
@emilsvedjer @robinflyman @akaraiskou could one of you / some of you attempt to replicate and see if your output is more like mine or more like Isak's?

**Comment by robinflyman** [comment]
I tested both your variants (if it would've made any difference) and 'id' showed up both times.

**Comment by jamesramsden-bh** [comment]
Closing, cannot replicate my original 'issue' on my machine! Thanks @IsakNaslundBh and @robinflyman for your input.
