### ISSUE TITLE
Updated READMEs across repos

### ISSUE THREAD

**Issue by al-fisher** [BHoM/admin#4]
As discussed need to create a new series of standard templates based on the types of Toolkits.
README's need a review and update anyway and standardising will make sure we capture important info on all (where needed), point to refreshed wiki, but also with some repo specific info were needed.

An extra benefit of implementing a standard format, with known markdown headers means we can scrape some info into upcoming API, much like our changelog is from PRs, if desired.

Can have different readme templates for different types of toolkits:

- [ ] "Core"
- [ ] "Discipline/Engine"
- [ ] "Software/Adapter/UI"

Capturing iterations with @FraserGreenroyd _el al._ propose standardising the following sections - using Robot_Toolkit as an example below.

----

[![License: LGPL v3](https://img.shields.io/badge/License-LGPL%20v3-blue.svg)](https://www.gnu.org/licenses/lgpl-3.0) [![Build status](https://ci.appveyor.com/api/projects/status/11a3ucotxcl9746k/branch/master?svg=true)](https://ci.appveyor.com/project/BHoMBot/robot-toolkit/branch/master) [![Build Status](https://dev.azure.com/BHoMBot/BHoM/_apis/build/status/Robot_Toolkit/Robot_Toolkit.CheckCore?branchName=master)](https://dev.azure.com/BHoMBot/BHoM/_build/latest?definitionId=93&branchName=master)

# Robot_Toolkit

Description of the toolkit and any useful information or example usage. Something like : this toolkit allows interoperability between the BHoM and Autodesk Robot Structural Analysis. Enables creation, manipulation and reading of structural finite element analysis models and analysis results. Etc.
...

https://www.autodesk.co.uk/products/robot-structural-analysis 

### Known Versions of Software Supported
Autodesk Robot Structural Analysis Professional 2018
Autodesk Robot Structural Analysis Professional 2019

### Documentation
For more information about functionality see (_links to Toolkit specific Wiki and/or API when ready_)

---
This toolkit is part of the Buildings and Habitats object Model. Find out more on our [wiki](https://github.com/BHoM/documentation/wiki) or at [https://bhom.xyz](https://bhom.xyz/)

## Quick Start 🚀 

Grab the [latest installer](https://bhom.xyz/) and a selection of [sample scripts](https://github.com/BHoM/samples).

## Getting Started for Developers 🤖 

If you want to build the BHoM and the Toolkits from source, it's hopefully easy! 😄 
Do take a look at our specific wiki pages here: [Getting Started for Developers](https://github.com/BHoM/documentation/wiki/Getting-started-for-developers)

## Want to Contribute? ##

BHoM is an open-source project and would be nothing without its community. Take a look at our contributing guidelines and tips [here](https://github.com/BHoM/BHoM/blob/master/CONTRIBUTING.md).

## Licence ##

BHoM is free software licenced under GNU Lesser General Public Licence - [https://www.gnu.org/licenses/lgpl-3.0.html](https://www.gnu.org/licenses/lgpl-3.0.html)  
Each contributor holds copyright over their respective contributions.
The project versioning (Git) records all such contribution source information.
See [LICENSE](https://github.com/BHoM/BHoM/blob/master/LICENSE) and [COPYRIGHT_HEADER](https://github.com/BHoM/BHoM/blob/master/COPYRIGHT_HEADER.txt).

**Comment by al-fisher** [comment]
Have completed updates to the following repos:
- [x] BHoM
- [x] BHoM_Engine
- [x] BHoM_Adapter
- [x] BHoM_UI
- [ ] Socket_Toolkit
- [x] TriangleNet_Toolkit
- [x] Clipper_Toolkit
- [x] HTTP_Toolkit
- [x] Localisation_Toolkit
- [x] CarbonQueryDatabase_Toolkit
- [ ] ClimateEmergency_Toolkit
- [ ] CSharp_Toolkit
- [x] DIALux_Toolkit
- [ ] ETABS_Toolkit
- [x] GSA_Toolkit
- [x] IES_Toolkit
- [ ] LifeCycleAssessment_Toolkit
- [x] Lusas_Toolkit
- [x] MidasCivil_Toolkit
- [ ] Mongo_Toolkit
- [ ] RAM_Toolkit
- [x] Revit_Toolkit
- [ ] RFEM_Toolkit
- [ ] Rhinoceros_Toolkit
- [ ] Robot_Toolkit
- [ ] SAP2000_Toolkit
- [x] TAS_Toolkit
- [ ] Versioning_Toolkit
- [x] XML_Toolkit
- [ ] Grasshopper_Toolkit
- [ ] Dynamo_Toolkit
- [ ] Excel_Toolkit

**Comment by al-fisher** [comment]
@FraserGreenroyd @IsakNaslundBh @pawelbaran @alelom as discussed - added a list to pick a few to tick off next sprint. Based on template above

**Comment by pawelbaran** [comment]
@al-fisher I am almost there with Revit_Toolkit, however cannot find out how to find project number of Revit_Toolkit in this line: https://ci.appveyor.com/api/projects/status/11a3ucotxcl9746k/branch/master?svg=true (I guess 11a3ucotxcl9746k is specific to Robot_Toolkit and should be replaced with Revit_Toolkit?)

[![Build status](https://ci.appveyor.com/api/projects/status/11a3ucotxcl9746k/branch/master?svg=true)](https://ci.appveyor.com/project/BHoMBot/robot-toolkit/branch/master)

**Comment by al-fisher** [comment]
Ah - thanks @pawelbaran - let me look at this now 😄

**Comment by FraserGreenroyd** [comment]
I will raise some issues for the outstanding toolkits this morning. This checklist is to help me get the correct AppVeyor badges as appropriate.

Have completed updates to the following repos:

- [x] BHoM_UI
- [x] Socket_Toolkit
- [x] TriangleNet_Toolkit
- [x] Clipper_Toolkit
- [x] HTTP_Toolkit
- [x] Localisation_Toolkit
- [x] ClimateEmergency_Toolkit
- [x] CSharp_Toolkit
- [x] DIALux_Toolkit
- [x] ETABS_Toolkit
- [x] GSA_Toolkit
- [x] IES_Toolkit
- [x] LifeCycleAssessment_Toolkit
- [x] Lusas_Toolkit
- [x] MidasCivil_Toolkit
- [x] Mongo_Toolkit
- [x] RAM_Toolkit
- [x] RFEM_Toolkit
- [x] Rhinoceros_Toolkit
- [x] Robot_Toolkit
- [x] SAP2000_Toolkit
- [x] TAS_Toolkit
- [x] Versioning_Toolkit
- [x] XML_Toolkit
- [x] Grasshopper_Toolkit
- [x] Dynamo_Toolkit
- [x] Excel_Toolkit

**Comment by FraserGreenroyd** [comment]
All issues raised with suitable AppVeyor badges assigned for people to begin filling in/closing out.

**Comment by FraserGreenroyd** [comment]
FYI: @adecler @IsakNaslundBh and anyone else assigned an issue, be aware I have provided only the AppVeyor badges which are not easily accessible, but the Azure ones are publicly available so hopefully everyone can get the correct badges ok :smile:

**Comment by FraserGreenroyd** [comment]
@al-fisher can we update the status of this issue with help from others as appropriate? Would be good to finally close this out as completed, as I suspect most are now done if not ticked off? :smile:

**Comment by al-fisher** [comment]
Happy to close - with Excel_Toolkit the remaining repo (and issue already raised and bumped)

Thanks @FraserGreenroyd
