### ISSUE TITLE
AppVeyor fails CI check on BHoM tags

### ISSUE THREAD

**Issue by al-fisher** [BHoM/admin#6]
#### Description:
It seems that AppVeyor fails to successfully clone our beta tagged commits. It looks like it might be struggling to get the "branch" due to special character. Unsure. 
See examples https://ci.appveyor.com/project/BHoMBot/bhom-ui/builds/33823082 or https://ci.appveyor.com/project/BHoMBot/bhom/builds/33736085

This is not actually critical - as retriggering AppVeyor on the actual `master` (same commit) - will be successful.

It is however showing CI failures on release until manually triggered or a new commit is merged - so will be useful to resolve at some point.

@FraserGreenroyd FYI

**Comment by FraserGreenroyd** [comment]
Wrapping the branch name (tag name in this case) in speech marks would probably resolve this, just need to amend the AppVeyor workflow to do so I suspect similar to the Azure workflow.

Something to look at during this milestone ready for 3.3 release for sure!

**Comment by FraserGreenroyd** [comment]
AppVeyor is no longer used as part of our CI/CD strategy so closing this issue for now 😄
